server:
  port: 7070
jsf:
  FACELETS_DECORATORS: de.beyondjava.angularFaces.core.tagTransformer.AngularTagDecorator
  primefaces:
    THEME: bootstrap
    FONT_AWESOME: true
  bootsfaces:
    USETHEME: true